name: checktrack
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  syncfusion_flutter_gauges: ^22.1.38
  socket_io_client: ^2.0.2
  indexed: ^0.0.8
  better_page_turn: ^0.0.6
  page_flip_builder: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  http: ^0.13.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/